metadata_dir = "/meta"
data_dir = "/data"
db_engine = "sqlite"

replication_factor = "1"
replication_mode = "1"

rpc_bind_addr = "0.0.0.0:3901"
rpc_public_addr = "127.0.0.1:3901"
rpc_secret = "4c8e6ca7e6c7d4c5a6e8b9c7e6c5d4c3b2a1e0f9e8d7c6b5a4b3c2d1e0f9e8d7"

[s3_api]
s3_region = "garage"
api_bind_addr = "0.0.0.0:3900"
root_domain = ".s3.garage.localhost"

[s3_web]
bind_addr = "0.0.0.0:3902"
root_domain = ".web.garage.localhost"

[admin]
api_bind_addr = "0.0.0.0:3903"
admin_token = "garage-admin-token-2024"
metrics_token = "garage-metrics-token-2024"